version: "3.9"

services:
  store-db:
    image: postgres:16.1
    restart: always
    container_name: store-db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/data/postgresql

volumes:
  pgdata:
